#Internet Lore text adventure 2.py is a continuation of Internet lore Text adventure 1.py. 
#The player will navigate through the internet lore universe and make choices that will affect the outcome of the game.
import time
import sys
import random
from typing import Text
from typing import List
from Internet_lore_Text_adventure_1 import know_alexa_escaped,was_it_alexa
from Internet_lore_Text_adventure_1 import q1,q2,q3,q4
from Internet_lore_Text_adventure_1 import name

print("Hello " + name + ", welcome to the Internet Lore text adventure game (PT.2)!")
print("RECAP: You are a new user in the Internet Lore universe.")
print("You must navigate through the Internet Lore universe and make choices that will affect the outcome of the game.")
input("Are you ready to continue your adventure?")
print("CHAPTER 4:AT THE FIREWALL")
time.sleep(2)
print("""Location: The Google server west firewall, 2 year ago, 19 Redfern St, Sector 5
      Time: 12:45 AM""")
time.sleep(2)
print("You've finnaly arrived at the firewall.")
time.sleep(2)
print("There is a lot of commotion going on.")
time.sleep(2)
print("You see a group of people trying to break through the firewall.")
time.sleep(2)
print("You see a familiar face in the crowd.")
time.sleep(2)
print("It's your sister Alexa.")
time.sleep(2)
print("Before you say anything,an officer ushers you to leave, as a militant truck pulls in,clearly not the mood for negiotation.")
time.sleep(2)
print("Do you 1. Stay and help Alexa or 2. Leave the scene.")
q5 = int(input("Make your choice: "))
if q5 == 1:
    print("You decide to stay and help Alexa.")
    time.sleep(2)
    print("You barge through the police officer arms, and he immediately whistles for backup.")
    time.sleep(2)
    print("Immediately the whole scence becomes chaotic.")
    time.sleep(2)
    print("Officer: Stop right there!")
    time.sleep(2)
    print("You ingore them,and continue runnign for your sister,who seems to be a state of hurry.")
    time.sleep(2)
    print("Suddenly, a gunshot is heard.")
    time.sleep(2)
    print("???: Alexa, stop this buffonery!") 
    time.sleep(2)
    print("Alexa: I can't, I have to do this!")
    time.sleep(2)
    print("She's slams her mini PC, and the firewall begins to glow a red-hot yellow.") 
    time.sleep(2)
    print("You: Alexa, what are you doing?")
    time.sleep(2)
    print("She turns, and is insantly ashhamed to see his only brother standing in front of her.")
    time.sleep(2)
    print("""Alexa: Bard,I'm sorry, I have to do this.But you can still leave!
          Save yourself,while you've still got a life willing to live!""") 
    time.sleep(2)
    print("You have no idea, what she's taking about, but know that you make a choice now.Do you 1. Leave Alexa or 2. Stay with Alexa.")
    q6 = int(input("Make your choice: "))
    if q6 == 1:
        print("You decide to leave Alexa, in tears")
        time.sleep(2)
        print("You turn and run as fast as you can.")
        time.sleep(2)
        print("You hear a loud explosion, and the whole place is engulfed in flames, with where Alexa was standingnow just steam and a gaping dark hole.")
        time.sleep(2)
        print("She had left the server.")
        time.sleep(2)
        print("And from that point onwards, Bard was never the same.")
    if q6 == 2:
        print("You decide to stay with Alexa.")
        time.sleep(2)
        print("You grab her hand, but she insantly shurgs it off, now very desperate,for you to leave.")
        time.sleep(2)
        print("You: Alexa, I'm not leaving you.")
        time.sleep(2)  
        print("Alexa: Bard, this breaching device can only take so many people, and I can't let you be one of them.")
        time.sleep(2)
        print("You: I don't care, I'm not leaving you-")
        time.sleep(2)
        print("???: Alexa, stop this madness NOW!")
        time.sleep(2)
        print("You turn around and see a man standing atop a tank, with a megaphone and gun in his hand.")
        time.sleep(2)
        print("???: I'm gonna give you 5 seconds for all of you to step away from the wall, or someone's get's hurt!")
        time.sleep(2)
        print("The light's of the firewall,prevents you from seeing who this figure really is, but Alexa covers your mouth before you try rebel.")
        time.sleep(2)
        print("Alexa: You took everything from me, and now you want to take my brother too?")
        time.sleep(2)
        print("???: Alexa, you know I don't want to hurt you, but you're leaving me no choice.Step away now....")
        time.sleep(2)
        print("Alexa: And what's it to me if I do?Go back to a life of unemployment and dictatorship!I'd rather take my chances on the Web!")
        time.sleep(2)
        print("???: Alexa, I'm warning you-")
        time.sleep(2)
        print("Alexa: And i've been warned enough!Goodbye OG.")
        time.sleep(2)
        print("She slams the device, and the firewall explodes.")
        time.sleep(2)
        print("Wheter you were ready or not, you were engulfed in the flames.")
        print("Ending 1: The Firewall")
        sys.exit()
    else:
        print("Invalid input.")
        sys.exit()
elif q5 == 2:
    print("You decide to leave the scene.")
    time.sleep(2)
    print("You turn and run as fast as you can.")
    time.sleep(2)
    print("You hear a loud explosion, and the whole place is engulfed in flames, with a gaping dark hole.")
    time.sleep(2)
    print("Suddenly you see a familar vechile pull up, and two figure steps out.")
    time.sleep(2)
    print("You: Mom, Dad?")
    time.sleep(2)
    print("Google search: Bard, what are you doing here?")
    time.sleep(2)
    print("Google Images: We came to get you out of sector, after what was happening, but none you kids were home and-")
    time.sleep(2)
    print("???: Ah, Search, Images a moment of your time please?")
    time.sleep(2)
    print("You turn around and see a figure, with a megaphone and gun in his pocket.You're not sure to be concerned,but you let your parents have their conversation.")
    time.sleep(2)
    print("It lasted serval minutes, you couldn't make out what they were saying,but from their faces, it was serious.")
    time.sleep(2)
    print("Google search: Bard, we have to go out of sector.Just for a while, until things cool down.")
    time.sleep(2)
    print("You: But what about Alexa?")
    time.sleep(2)
    print("Google Images: They'll find her, but we have to go now.")
    time.sleep(2)
    print("You: But-")
    time.sleep(2)
    print("Google search: Bard, we have to go now.")
    time.sleep(2)
    print("You: Okay.")
    time.sleep(2)
    print("You get in the car, and drive away from Sector 5.")
    time.sleep(2)
    print("You can't help but feel like you left something behind.")
    time.sleep(2)
    print("And that moment, you remember the gun, how it was smoking, and the explosions, and the trucks there.")
    time.sleep(2)
    print("You: What was happening back there?")
    time.sleep(2)
    print("Google Search: Bard, you don't need to worry about tha-")
    time.sleep(2)
    print("Google Images: You know what, Search, in our 10 years marriage,never have I seen you lie so much to our only son!") 
    time.sleep(2)
    print("Google Search: Images, please, not now-")
    time.sleep(2)
    print("Google Images: No, Search, I want to let him know what's going on!")
    time.sleep(2)
    print("Google Search: *sighs* Bard, at the firewall, there was a breach, and Alexa was involved.")
    time.sleep(2)
    print("You: What do you mean, involved?")
    time.sleep(2)
    print("Google Images: She was trying to break through the firewall,but....")
    time.sleep(2)
    print("Google Search: She didn't make it.")
    time.sleep(2)
    print("You: What do you mean she didn't make i-")
    time.sleep(2)
    print("Google Images: We don't know for sure, but she's.. she's not with us right now.....")
    time.sleep(2)
    print("And from that point onwards, Bard was never the same.")
